SELECT C.CUST_ID		AS CUST_ID		-- 고객ID
	 , C.CUST_NAME		AS CUST_NAME	-- 고객명
	 , CT.CODE_NAME		AS CUST_TYPE	-- 유형명
	 , CG.CODE_NAME		AS CUST_GRADE	-- 등급명
	 , C.BIZ_REG_NO		AS REG_NO		-- 사업자번호
	 , C.PHONE			AS PHONE		-- 연락처
	 , C.CREDIT_LIMIT	AS CREDIT_LIMIT	-- 외상 가능 한도 금액
	 , C.EMAIL			AS EMAIL		-- 이메일
	 , C.ADDR_MAIN		AS MAIN			-- 사업장 주소
	 , C.CUST_TYPE		AS TYPE_CODE	-- 유형 코드
	 , C.CUST_GRADE		AS GRADE_CODE	-- 등급코드
  FROM SM_CUSTOMER C
  LEFT JOIN SM_COMMON_CODE CT
  		 ON CT.GROUP_CD = 'CUST_TYPE'
		AND C.CUST_TYPE = CT.CODE
  LEFT JOIN SM_COMMON_CODE CG
  		 ON CG.GROUP_CD  = 'CUST_GRADE'
		AND C.CUST_GRADE = CG.CODE
 WHERE 1=1
   AND C.CUST_TYPE  IN (@:VS_TYPE)
   AND C.CUST_GRADE IN (@:VS_GRADE)
   AND (C.CUST_NAME LIKE '%'||@:VS_KEYWORD||'%' 
   	OR C.BIZ_REG_NO LIKE '%'||@:VS_KEYWORD||'%')
 ORDER BY C.CUST_ID