SELECT    T1.FOLDER_CODE 		AS FOLDER_CODE 
 		, T1.FOLDER_NAME 		AS FOLDER_NAME 
		, CASE WHEN T1.FOLDER_CODE ='DEFAULT' THEN 'DEFAULT'
		  ELSE  T1.PARENT_FOLDER_CODE END PARENT_FOLDER_CODE 
		, 'F0' AS IMG_FILE
 FROM MTX_FOLDER T1   
 ORDER BY T1.FOLDER_SEQ

	 