@@CSV
ID,PARENT_ID,NAME,TITLE
CEO,,홍길동,대표이사
CTO,CEO,김철수,기술이사
CFO,CEO,이영희,재무이사
COO,CEO,박운영,운영이사
DEV_LEAD,CTO,최개발,개발팀장
INFRA_LEAD,CTO,정인프라,인프라팀장
FE1,DEV_LEAD,강프론트,프론트엔드
BE1,DEV_LEAD,윤백엔드,백엔드
BE2,DEV_LEAD,임서버,백엔드
INFRA1,INFRA_LEAD,한클라우드,클라우드엔지니어
INFRA2,INFRA_LEAD,오네트워크,네트워크엔지니어
FIN_LEAD,CFO,송재무,재무팀장
ACC1,FIN_LEAD,조회계,회계담당
ACC2,FIN_LEAD,배세무,세무담당
OPS_LEAD,COO,나운영,운영팀장
CS1,OPS_LEAD,마고객,고객지원
CS2,OPS_LEAD,사서비스,서비스기획
