SELECT SP.SALES_ID AS SALES_ID
	 , TO_CHAR(SP.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
	 , E.EMP_NAME AS EMP_NAME
	 , C.CUST_NAME AS CUST_NAME
	 , P.PROD_NAME AS PROD_NAME
	 , SP.QTY AS QTY
	 , SP.UNIT_PRICE AS UNIT_PRICE
	 , SP.COST_AMOUNT AS COST_AMOUNT
	 , CG.CODE_NAME AS SALES_STATUS
  FROM SM_SALES_PERFORMANCE	SP
LEFT JOIN SM_EMPLOYEE	E
	   ON SP.EMP_ID = E.EMP_ID
LEFT JOIN SM_CUSTOMER	C
	   ON SP.CUST_ID = C.CUST_ID
LEFT JOIN SM_PRODUCT	P
	   ON SP.PROD_ID = P.PROD_ID
LEFT JOIN SM_COMMON_CODE CG
	   ON CG.GROUP_CD = 'SALES_STATUS'
	  AND SP.SALES_STATUS = CG.CODE
 WHERE 1=1
   AND SP.SALES_DATE BETWEEN (@:VS_YMD_FROM) AND (@:VS_YMD_TO)
   AND SP.EMP_ID IN (@:VS_PIC)
   AND SP.CUST_ID IN (@:VS_CUST)
   AND SP.SALES_STATUS IN (@:VS_STATUS)