SELECT RN
     , CUST_NAME
     , CUST_TYPE
     , SALES_AMOUNT
     , SALES_AMOUNT / NULLIF(TOTAL_SALES,0) AS SALES_RATIO
  FROM (
		SELECT ROW_NUMBER() OVER (ORDER BY SUM(S.NET_AMOUNT) DESC) AS RN
			 , C.CUST_NAME
			 , CM.CODE_NAME AS CUST_TYPE
			 , SUM(S.NET_AMOUNT) AS SALES_AMOUNT
			 , SUM(SUM(S.NET_AMOUNT)) OVER () AS TOTAL_SALES
		  FROM SM_SALES_PERFORMANCE S
		  LEFT JOIN SM_CUSTOMER C
			ON S.CUST_ID = C.CUST_ID
		  LEFT JOIN SM_COMMON_CODE CM
			ON CM.GROUP_CD = 'CUST_TYPE'
		   AND C.CUST_TYPE = CM.CODE
		 WHERE TO_CHAR(S.SALES_DATE,'YYYY') = :VS_YEAR
		 GROUP BY C.CUST_NAME, CM.CODE_NAME
		) T
  WHERE RN <= :VN_RANK_CST
  ORDER BY RN