SELECT 'Q'||Q.QUARTER AS QUARTER
	 , Q.TARGET_AMOUNT AS TARGET
     , Q.ACTUAL_AMOUNT AS ACTUAL
     , Q.ACTUAL_AMOUNT / NULLIF(Q.TARGET_AMOUNT, 0) AS ACHIEVEMENT_RATE
  FROM (
			SELECT EXTRACT(QUARTER FROM S.SALES_DATE) AS QUARTER
				 , SUM(P.TARGET_QTY * P.TARGET_AMT) AS TARGET_AMOUNT
				 , SUM(S.NET_AMOUNT) AS ACTUAL_AMOUNT
			  FROM SM_SALES_PERFORMANCE S
			  LEFT JOIN SM_SALES_PLAN P
				ON S.PROD_ID = P.PROD_ID
			 WHERE EXTRACT(YEAR FROM S.SALES_DATE) = :VS_YEAR
			 GROUP BY EXTRACT(QUARTER FROM S.SALES_DATE)
		) Q
 ORDER BY QUARTER