SELECT 'SALES-' || SUBSTR(:VS_YMD_TO,1,4) || '-'
       || RIGHT('0000' 
            	|| (COALESCE(MAX(CAST(SUBSTRING(SALES_ID, 12, 4) AS INTEGER)),0) + 1)::TEXT
          		, 4) AS SALES_ID
FROM SM_SALES_PERFORMANCE
WHERE SUBSTRING(SALES_ID, 7, 4) = SUBSTR(:VS_YMD_TO,1,4)