@@CSV
ID,PARENT_ID,NAME
ROOT,,Technology
FE,ROOT,Frontend
BE,ROOT,Backend
DB,ROOT,Database
DEVOPS,ROOT,DevOps
FE_REACT,FE,React
FE_VUE,FE,Vue
FE_ANGULAR,FE,Angular
FE_SVELTE,FE,Svelte
FE_REACT_NEXT,FE_REACT,Next.js
FE_REACT_REMIX,FE_REACT,Remix
FE_VUE_NUXT,FE_VUE,Nuxt.js
FE_ANGULAR_UNI,FE_ANGULAR,Angular Universal
BE_NODE,BE,Node.js
BE_JAVA,BE,Java
BE_PYTHON,BE,Python
BE_GO,BE,Go
BE_NODE_EXPRESS,BE_NODE,Express
BE_NODE_NEST,BE_NODE,NestJS
BE_JAVA_SPRING,BE_JAVA,Spring Boot
BE_JAVA_QUARKUS,BE_JAVA,Quarkus
BE_PYTHON_DJANGO,BE_PYTHON,Django
BE_PYTHON_FAST,BE_PYTHON,FastAPI
BE_GO_GIN,BE_GO,Gin
DB_MYSQL,DB,MySQL
DB_PG,DB,PostgreSQL
DB_MONGO,DB,MongoDB
DB_REDIS,DB,Redis
DEVOPS_DOCKER,DEVOPS,Docker
DEVOPS_K8S,DEVOPS,Kubernetes
DEVOPS_CICD,DEVOPS,CI/CD
DEVOPS_CICD_GHA,DEVOPS_CICD,GitHub Actions
DEVOPS_CICD_JENKINS,DEVOPS_CICD,Jenkins
