SELECT 1-CAST(SUM(CASE WHEN SALES_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS NUMERIC)/NULLIF(COUNT(SALES_ID),0) AS UNDER_RATE
	 , CAST(SUM(CASE WHEN SALES_STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS NUMERIC)/NULLIF(COUNT(SALES_ID),0)   AS RATE
  FROM SM_SALES_PERFORMANCE
 WHERE 1=1
   AND TO_CHAR(SALES_DATE, 'YYYY') = :VS_YEAR