SELECT E.EMP_NAME		AS EMP_NAME 
, COUNT(PERF.EMP_ID)	AS EMP_ID
, SUM(PERF.NET_AMOUNT)  AS NET_AMOUNT
FROM SM_SALES_PERFORMANCE	PERF
LEFT JOIN SM_EMPLOYEE	E
ON PERF.EMP_ID = E.EMP_ID
WHERE TO_CHAR(PERF.SALES_DATE, 'YYYY')=:VS_YEAR
GROUP BY E.EMP_ID