/*
 * 영업관리 시스템 (Safe Column Names Version)
 */

-- 0. SM_COMMON_CODE (공통코드)
CREATE TABLE SM_COMMON_CODE (
    GROUP_CD     VARCHAR(50) NOT NULL,            -- 그룹 코드
    CODE         VARCHAR(50) NOT NULL,            -- 실제 코드
    CODE_NAME    VARCHAR(256) NOT NULL,           -- 코드명
    CODE_DESC    VARCHAR(1024),                   -- 코드 설명
    SORT_ORDER   INTEGER DEFAULT 0,               -- 정렬 순서
    USE_YN       VARCHAR(1) DEFAULT 'Y' CHECK (USE_YN IN ('Y', 'N')),
    ATTR1        VARCHAR(256),                    -- 추가 속성1
    ATTR2        VARCHAR(256),                    -- 추가 속성2
    ATTR3        VARCHAR(256),                    -- 추가 속성3
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50),
    PRIMARY KEY (GROUP_CD, CODE)
);

COMMENT ON TABLE SM_COMMON_CODE IS '공통코드 관리 테이블';
COMMENT ON COLUMN SM_COMMON_CODE.GROUP_CD IS '그룹 코드 (예: PROD_CATEGORY, STD_UNIT, PLAN_STATUS)';
COMMENT ON COLUMN SM_COMMON_CODE.CODE IS '실제 코드값';
COMMENT ON COLUMN SM_COMMON_CODE.CODE_NAME IS '코드 표시명';
COMMENT ON COLUMN SM_COMMON_CODE.CODE_DESC IS '코드 상세 설명';
COMMENT ON COLUMN SM_COMMON_CODE.SORT_ORDER IS '화면 표시 정렬 순서';
COMMENT ON COLUMN SM_COMMON_CODE.USE_YN IS '사용 여부 (Y:사용, N:미사용)';
COMMENT ON COLUMN SM_COMMON_CODE.ATTR1 IS '추가 속성1 (확장용)';
COMMENT ON COLUMN SM_COMMON_CODE.ATTR2 IS '추가 속성2 (확장용)';
COMMENT ON COLUMN SM_COMMON_CODE.ATTR3 IS '추가 속성3 (확장용)';
COMMENT ON COLUMN SM_COMMON_CODE.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_COMMON_CODE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_COMMON_CODE.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_COMMON_CODE.UPDATED_BY IS '수정자';


-- 1. SM_DEPARTMENT (부서)
CREATE TABLE SM_DEPARTMENT (
    DEPT_ID        VARCHAR(50) PRIMARY KEY,
    DEPT_NAME      VARCHAR(256) NOT NULL,
    PARENT_DEPT_ID VARCHAR(50),        -- 상위 부서
    MANAGER_ID     VARCHAR(50),        -- 부서장 사번
    USE_YN         VARCHAR(1) DEFAULT 'Y' CHECK (USE_YN IN ('Y', 'N')),
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     VARCHAR(50),
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     VARCHAR(50)
    --,    CONSTRAINT FK_SM_DEPT_PARENT FOREIGN KEY (PARENT_DEPT_ID) REFERENCES SM_DEPARTMENT(DEPT_ID)
);

COMMENT ON TABLE SM_DEPARTMENT IS '조직 내 부서 및 팀 정보 관리';
COMMENT ON COLUMN SM_DEPARTMENT.DEPT_ID IS '부서 코드 (PK)';
COMMENT ON COLUMN SM_DEPARTMENT.DEPT_NAME IS '부서 명칭';
COMMENT ON COLUMN SM_DEPARTMENT.PARENT_DEPT_ID IS '상위 부서 코드 (Self Join)';
COMMENT ON COLUMN SM_DEPARTMENT.MANAGER_ID IS '부서장 사번';
COMMENT ON COLUMN SM_DEPARTMENT.USE_YN IS '부서 운영 여부 (Y:운영중, N:폐쇄)';
COMMENT ON COLUMN SM_DEPARTMENT.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_DEPARTMENT.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_DEPARTMENT.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_DEPARTMENT.UPDATED_BY IS '수정자';


-- 2. SM_EMPLOYEE (직원)
CREATE TABLE SM_EMPLOYEE (
    EMP_ID       VARCHAR(50) PRIMARY KEY,
    DEPT_ID      VARCHAR(50) NOT NULL,
    EMP_NAME     VARCHAR(256) NOT NULL,
    JOB_GRADE    VARCHAR(50),
    JOB_ROLE     VARCHAR(50),          -- 직무 
    COMM_PCT     NUMERIC(4, 2),        -- 인센티브 비율
    EMAIL        VARCHAR(100),
    PHONE        VARCHAR(20),
    EMP_STATUS   VARCHAR(50) DEFAULT 'ACTIVE',
    HIRE_DATE    TIMESTAMP,
    RETIRE_DATE  TIMESTAMP,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
    --,   CONSTRAINT FK_SM_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES SM_DEPARTMENT(DEPT_ID)
    --,CONSTRAINT FK_SM_EMP_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES SM_EMPLOYEE(EMP_ID)
);

COMMENT ON TABLE SM_EMPLOYEE IS '임직원 정보 및 인사 관리';
COMMENT ON COLUMN SM_EMPLOYEE.EMP_ID IS '사원 번호 (PK)';
COMMENT ON COLUMN SM_EMPLOYEE.DEPT_ID IS '소속 부서 코드 (FK)';
COMMENT ON COLUMN SM_EMPLOYEE.EMP_NAME IS '직원 성명';
COMMENT ON COLUMN SM_EMPLOYEE.JOB_GRADE IS '직급 (사원, 대리, 과장 등)';
COMMENT ON COLUMN SM_EMPLOYEE.JOB_ROLE IS '담당 직무 (영업, 마케팅, 지원 등)'; 
COMMENT ON COLUMN SM_EMPLOYEE.COMM_PCT IS '영업 인센티브 비율 (예: 0.1)';
COMMENT ON COLUMN SM_EMPLOYEE.EMP_STATUS IS '재직 상태 (ACTIVE, LEAVE, RETIRED)';
COMMENT ON COLUMN SM_EMPLOYEE.HIRE_DATE IS '입사일';
COMMENT ON COLUMN SM_EMPLOYEE.RETIRE_DATE IS '퇴사일';
COMMENT ON COLUMN SM_EMPLOYEE.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_EMPLOYEE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_EMPLOYEE.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_EMPLOYEE.UPDATED_BY IS '수정자';


-- 3. SM_CUSTOMER (고객)
CREATE TABLE SM_CUSTOMER (
    CUST_ID      VARCHAR(50) PRIMARY KEY,
    CUST_NAME    VARCHAR(256) NOT NULL,
    BIZ_REG_NO   VARCHAR(20),
    CUST_TYPE    VARCHAR(50),
    CUST_GRADE   VARCHAR(50),
    CREDIT_LIMIT NUMERIC(15, 2),
    PHONE        VARCHAR(20),
    EMAIL        VARCHAR(100),
    ADDR_MAIN    VARCHAR(255),
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
);

COMMENT ON TABLE SM_CUSTOMER IS '거래처 및 고객 마스터 정보';
COMMENT ON COLUMN SM_CUSTOMER.CUST_ID IS '고객 ID (PK)';
COMMENT ON COLUMN SM_CUSTOMER.CUST_NAME IS '고객명/회사명';
COMMENT ON COLUMN SM_CUSTOMER.BIZ_REG_NO IS '사업자 등록 번호';
COMMENT ON COLUMN SM_CUSTOMER.CUST_TYPE IS '고객 유형 (법인, 개인, 공공)';
COMMENT ON COLUMN SM_CUSTOMER.CUST_GRADE IS '고객 등급 (VIP, GOLD, SILVER)';
COMMENT ON COLUMN SM_CUSTOMER.CREDIT_LIMIT IS '외상 가능 한도 금액';
COMMENT ON COLUMN SM_CUSTOMER.ADDR_MAIN IS '사업장 주소';
COMMENT ON COLUMN SM_CUSTOMER.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_CUSTOMER.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_CUSTOMER.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_CUSTOMER.UPDATED_BY IS '수정자';


-- 4. SM_PRODUCT (상품)
CREATE TABLE SM_PRODUCT (
    PROD_ID      VARCHAR(50) PRIMARY KEY,
    PROD_NAME    VARCHAR(256) NOT NULL,
    CATEGORY     VARCHAR(50),
    STD_UNIT     VARCHAR(50),
    COST_PRICE   NUMERIC(15, 2),
    STD_PRICE    NUMERIC(15, 2) NOT NULL,
    SALE_YN      VARCHAR(1) DEFAULT 'Y' CHECK (SALE_YN IN ('Y', 'N')), -- [변경] IS_SALE -> SALE_YN
    PROD_DESC    VARCHAR(1024),
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
);

COMMENT ON TABLE SM_PRODUCT IS '판매 상품 마스터 정보';
COMMENT ON COLUMN SM_PRODUCT.PROD_ID IS '상품 코드 (PK)';
COMMENT ON COLUMN SM_PRODUCT.PROD_NAME IS '상품명';
COMMENT ON COLUMN SM_PRODUCT.CATEGORY IS '카테고리';
COMMENT ON COLUMN SM_PRODUCT.STD_UNIT IS '재고 관리 단위 (EA, BOX, SET)';
COMMENT ON COLUMN SM_PRODUCT.COST_PRICE IS '매입 원가 (이익 분석용)';
COMMENT ON COLUMN SM_PRODUCT.STD_PRICE IS '표준 판매 단가';
COMMENT ON COLUMN SM_PRODUCT.SALE_YN IS '판매 가능 여부 (Y:판매중, N:판매중단)';
COMMENT ON COLUMN SM_PRODUCT.PROD_DESC IS '상품 상세 설명';
COMMENT ON COLUMN SM_PRODUCT.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_PRODUCT.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_PRODUCT.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_PRODUCT.UPDATED_BY IS '수정자';


-- 5. SM_INVENTORY (재고)
CREATE TABLE SM_INVENTORY (
    INV_ID       VARCHAR(50) PRIMARY KEY,
    PROD_ID      VARCHAR(50) UNIQUE NOT NULL,
    CURR_QTY     INTEGER DEFAULT 0,
    SAFE_QTY     INTEGER DEFAULT 10,
    WAIT_IN_QTY  INTEGER DEFAULT 0,
    WAIT_OUT_QTY INTEGER DEFAULT 0,
    STORAGE_LOC  VARCHAR(50),
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
    --,   CONSTRAINT FK_SM_INV_PROD FOREIGN KEY (PROD_ID) REFERENCES SM_PRODUCT(PROD_ID)
);

COMMENT ON TABLE SM_INVENTORY IS '상품 재고 및 위치 관리';
COMMENT ON COLUMN SM_INVENTORY.INV_ID IS '재고 관리 번호 (PK, 예: INV-2024-001)';
COMMENT ON COLUMN SM_INVENTORY.PROD_ID IS '상품 코드 (FK)';
COMMENT ON COLUMN SM_INVENTORY.CURR_QTY IS '현재 가용 재고량';
COMMENT ON COLUMN SM_INVENTORY.SAFE_QTY IS '안전 재고 (발주점)';
COMMENT ON COLUMN SM_INVENTORY.WAIT_IN_QTY IS '입고 예정 수량';
COMMENT ON COLUMN SM_INVENTORY.WAIT_OUT_QTY IS '출고 대기 수량';
COMMENT ON COLUMN SM_INVENTORY.STORAGE_LOC IS '창고 내 적재 위치 (예: A-10-2)';
COMMENT ON COLUMN SM_INVENTORY.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_INVENTORY.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_INVENTORY.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_INVENTORY.UPDATED_BY IS '수정자';


-- 6. SM_SALES_PLAN (판매 계획)
CREATE TABLE SM_SALES_PLAN (
    PLAN_ID      VARCHAR(50) PRIMARY KEY,
    PLAN_YEAR    VARCHAR(4) NOT NULL,
    PLAN_MONTH   VARCHAR(2) NOT NULL,
    EMP_ID       VARCHAR(50) NOT NULL,
    PROD_ID      VARCHAR(50) NOT NULL,
    TARGET_QTY   INTEGER DEFAULT 0,
    TARGET_AMT   NUMERIC(15, 2) DEFAULT 0,
    PLAN_VER     INTEGER DEFAULT 1,
    PLAN_STATUS  VARCHAR(50) DEFAULT 'CONFIRMED',
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
    --,
    --CONSTRAINT FK_SM_PLAN_EMP FOREIGN KEY (EMP_ID) REFERENCES SM_EMPLOYEE(EMP_ID),
    --CONSTRAINT FK_SM_PLAN_PROD FOREIGN KEY (PROD_ID) REFERENCES SM_PRODUCT(PROD_ID)
);

COMMENT ON TABLE SM_SALES_PLAN IS '영업 목표 및 계획 관리';
COMMENT ON COLUMN SM_SALES_PLAN.PLAN_ID IS '계획 번호 (PK)';
COMMENT ON COLUMN SM_SALES_PLAN.PLAN_YEAR IS '계획 연도';
COMMENT ON COLUMN SM_SALES_PLAN.PLAN_MONTH IS '계획 월';
COMMENT ON COLUMN SM_SALES_PLAN.TARGET_QTY IS '목표 수량';
COMMENT ON COLUMN SM_SALES_PLAN.TARGET_AMT IS '목표 금액';
COMMENT ON COLUMN SM_SALES_PLAN.PLAN_VER IS '계획 버전 (수정 차수)';
COMMENT ON COLUMN SM_SALES_PLAN.PLAN_STATUS IS '계획 상태 (DRAFT, CONFIRMED)';
COMMENT ON COLUMN SM_SALES_PLAN.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_SALES_PLAN.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_SALES_PLAN.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_SALES_PLAN.UPDATED_BY IS '수정자';


-- 7. SM_SALES_PERFORMANCE (판매 실적)
CREATE TABLE SM_SALES_PERFORMANCE (
    SALES_ID     VARCHAR(50) PRIMARY KEY,
    SALES_DATE   TIMESTAMP NOT NULL,
    CUST_ID      VARCHAR(50) NOT NULL,
    EMP_ID       VARCHAR(50) NOT NULL,
    PROD_ID      VARCHAR(50) NOT NULL,

    UNIT_PRICE   NUMERIC(15, 2) NOT NULL,
    QTY          INTEGER NOT NULL,
    DISCOUNT_AMT NUMERIC(15, 2) DEFAULT 0,
    NET_AMOUNT   NUMERIC(15, 2) NOT NULL,
    TAX_AMOUNT   NUMERIC(15, 2) DEFAULT 0,
    COST_AMOUNT  NUMERIC(15, 2),

    PAY_METHOD   VARCHAR(50),
    SALES_STATUS VARCHAR(50) DEFAULT 'COMPLETED',
    REMARKS      VARCHAR(1024),
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(50),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   VARCHAR(50)
    --,
    --CONSTRAINT FK_SM_SALES_CUST FOREIGN KEY (CUST_ID) REFERENCES SM_CUSTOMER(CUST_ID),
    --CONSTRAINT FK_SM_SALES_EMP FOREIGN KEY (EMP_ID) REFERENCES SM_EMPLOYEE(EMP_ID),
    --CONSTRAINT FK_SM_SALES_PROD FOREIGN KEY (PROD_ID) REFERENCES SM_PRODUCT(PROD_ID)
);

COMMENT ON TABLE SM_SALES_PERFORMANCE IS '판매 실적 및 거래 내역 상세';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.SALES_ID IS '전표 번호 (PK)';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.SALES_DATE IS '거래 발생 일시';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.UNIT_PRICE IS '거래 시점 단가';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.DISCOUNT_AMT IS '총 할인 금액';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.NET_AMOUNT IS '실 매출액 (판매가-할인)';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.COST_AMOUNT IS '원가 합계 (이익 계산용)';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.PAY_METHOD IS '결제 수단';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.SALES_STATUS IS '판매 진행 상태 (COMPLETED, RETURN)';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.CREATED_BY IS '생성자';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.UPDATED_AT IS '수정 일시';
COMMENT ON COLUMN SM_SALES_PERFORMANCE.UPDATED_BY IS '수정자';


-- ============================================================
-- 공통코드 초기 데이터 (Initial Data for SM_COMMON_CODE)
-- ============================================================

-- JOB_GRADE: 직급 (사원, 대리, 과장 등)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', '$', '직급', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', 'STAFF', '사원', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', 'SENIOR', '대리', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', 'MANAGER', '과장', 3);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', 'DEPUTY', '차장', 4);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_GRADE', 'DIRECTOR', '부장', 5);

-- JOB_ROLE: 담당 직무 (영업, 마케팅, 지원 등)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_ROLE', '$', '담당 직무', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_ROLE', 'SALES', '영업', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_ROLE', 'MARKETING', '마케팅', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('JOB_ROLE', 'SUPPORT', '지원', 3);

-- EMP_STATUS: 재직 상태 (ACTIVE, LEAVE, RETIRED)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('EMP_STATUS', '$', '재직 상태', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('EMP_STATUS', 'ACTIVE', '재직중', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('EMP_STATUS', 'LEAVE', '휴직', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('EMP_STATUS', 'RETIRED', '퇴직', 3);

-- CUST_TYPE: 고객 유형 (법인, 개인, 공공)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_TYPE', '$', '고객 유형', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_TYPE', 'CORP', '법인', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_TYPE', 'PERSONAL', '개인', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_TYPE', 'PUBLIC', '공공', 3);

-- CUST_GRADE: 고객 등급 (VIP, GOLD, SILVER)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_GRADE', '$', '고객 등급', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_GRADE', 'VIP', 'VIP', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_GRADE', 'GOLD', 'GOLD', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('CUST_GRADE', 'SILVER', 'SILVER', 3);

-- PROD_CATEGORY: 상품 카테고리
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PROD_CATEGORY', '$', '상품 카테고리', 0);

-- STD_UNIT: 재고 관리 단위 (EA, BOX, SET)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('STD_UNIT', '$', '재고 관리 단위', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('STD_UNIT', 'EA', '개', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('STD_UNIT', 'BOX', '박스', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('STD_UNIT', 'SET', '세트', 3);

-- PLAN_STATUS: 계획 상태 (DRAFT, CONFIRMED)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PLAN_STATUS', '$', '계획 상태', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PLAN_STATUS', 'DRAFT', '초안', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PLAN_STATUS', 'CONFIRMED', '확정', 2);

-- PAY_METHOD: 결제 수단
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PAY_METHOD', '$', '결제 수단', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PAY_METHOD', 'CASH', '현금', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PAY_METHOD', 'CARD', '카드', 2);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PAY_METHOD', 'TRANSFER', '계좌이체', 3);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('PAY_METHOD', 'CREDIT', '외상', 4);

-- SALES_STATUS: 판매 진행 상태 (COMPLETED, RETURN)
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('SALES_STATUS', '$', '판매 진행 상태', 0);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('SALES_STATUS', 'COMPLETED', '완료', 1);
INSERT INTO SM_COMMON_CODE (GROUP_CD, CODE, CODE_NAME, SORT_ORDER) VALUES ('SALES_STATUS', 'RETURN', '반품', 2);