SELECT GROUP_CD			AS GROUP_CD
	 , MAX(CODE_NAME)	AS CODE_NAME
	 , COUNT(CODE)		AS CODE
	 , MAX(CODE_DESC)	AS CODE_DESC
	 , MAX(SORT_ORDER)	AS SORT_ORDER
  FROM SM_COMMON_CODE
 WHERE CODE <> '$'
 GROUP BY GROUP_CD
 ORDER BY SORT_ORDER