SELECT TO_CHAR(PFM.SALES_DATE,'YYYYMM') AS DATE
	 , SUM(PFM.NET_AMOUNT) AS ACTUAL
	 , SUM(PLN.TARGET_QTY*PLN.TARGET_AMT) AS TARGET
	 , SUM(PFM.NET_AMOUNT)/SUM(PLN.TARGET_QTY*PLN.TARGET_AMT)*100 AS RATE
  FROM SM_SALES_PERFORMANCE PFM
  LEFT JOIN SM_SALES_PLAN PLN
  	ON PFM.PROD_ID = PLN.PROD_ID
 WHERE TO_CHAR(PFM.SALES_DATE,'YYYY') = :VS_YEAR
 GROUP BY TO_CHAR(PFM.SALES_DATE,'YYYYMM')
 ORDER BY TO_CHAR(PFM.SALES_DATE,'YYYYMM')