SELECT P.CATEGORY
	 , SUM(PFM.NET_AMOUNT) AS ACTUAL
	 , SUM(PFM.NET_AMOUNT)/SUM(SUM(PFM.NET_AMOUNT)) OVER()	AS RATIO
  FROM SM_SALES_PERFORMANCE	PFM
  LEFT JOIN SM_PRODUCT	P
	ON PFM.PROD_ID = P.PROD_ID
 WHERE TO_CHAR(PFM.SALES_DATE,'YYYY') = :VS_YEAR
 GROUP BY P.CATEGORY
 ORDER BY P.CATEGORY