SELECT P.PROD_ID AS PROD_ID					
	 , P.PROD_NAME AS PROD_NAME			
	 , CG.CODE_NAME AS CATEGORY		
	 , P.STD_PRICE AS STD_PRICE		
	 , P.COST_PRICE AS COST_PRICE	
	 , P.STD_UNIT AS STD_UNIT	
	 , SP.SALES_STATUS AS SALES_STATUS
  FROM SM_PRODUCT	P
LEFT JOIN SM_COMMON_CODE	CG
	   ON CG.GROUP_CD = 'PROD_CATEGORY'
	  AND P.CATEGORY = CG.CODE
LEFT JOIN SM_SALES_PERFORMANCE	SP
	   ON P.PROD_ID = SP.PROD_ID
WHERE 1=1
  AND CG.CODE IN (@:VS_CAT)
  AND SP.SALES_STATUS IN (@:VS_STATUS)			
  AND (P.PROD_ID LIKE '%'||@:VS_KEYWORD||'%' 
   OR P.PROD_NAME LIKE '%'||@:VS_KEYWORD||'%')