SELECT E.EMP_ID		AS EMP_ID
	 , E.EMP_NAME	AS EMP_NAME
	 , D.DEPT_NAME	AS DEPT_NAME
	 , CG.CODE_NAME	AS POSITION
 	 , E.EMAIL		AS EMAIL
	 , E.PHONE		AS PHONE
	 , E.HIRE_DATE	AS HIRE_DATE
	 , CS.CODE_NAME	AS EMP_STATUS
	 , E.DEPT_ID	AS DEPT_CODE
	 , E.JOB_GRADE	AS POSITION_CODE
	 , E.EMP_STATUS AS EMP_STATUS_CODE
  FROM SM_EMPLOYEE E
 LEFT JOIN SM_DEPARTMENT D
 		ON E.DEPT_ID = D.DEPT_ID
 LEFT JOIN SM_COMMON_CODE CG
 		ON CG.GROUP_CD = 'JOB_GRADE'
	   AND E.JOB_GRADE = CG.CODE
 LEFT JOIN SM_COMMON_CODE CS
 		ON CS.GROUP_CD = 'EMP_STATUS'
	   AND E.EMP_STATUS = CS.CODE
 WHERE 1=1
   AND D.DEPT_ID IN (@:VS_DEPT)
   AND E.JOB_GRADE IN (@:VS_POSITION)
   AND E.EMP_STATUS IN (@:VS_STATUS)
   AND (E.EMP_ID LIKE '%'||@:VS_KEYWORD||'%' 
   	OR E.EMP_NAME LIKE '%'||@:VS_KEYWORD||'%')
 ORDER BY E.EMP_ID