SELECT CASE
        WHEN :VS_DEPT = '' THEN '전체'
        ELSE D.DEPT_NAME
       END 									AS DEPT_NAME                        
	 , TO_CHAR(PERF.SALES_DATE, 'YYYY-MM')	AS SALES_YM
	 , SUM(PLN.TARGET_AMT)					AS TARGET_AMT
     , SUM(PERF.NET_AMOUNT)					AS NET_AMOUNT
  FROM SM_SALES_PERFORMANCE PERF
  LEFT JOIN SM_SALES_PLAN PLN
    ON PLN.PROD_ID = PERF.PROD_ID
  LEFT JOIN SM_EMPLOYEE	E
    ON PERF.EMP_ID = E.EMP_ID
  LEFT JOIN SM_DEPARTMENT	D
    ON E.DEPT_ID = D.DEPT_ID
 WHERE 1=1
   AND D.DEPT_ID = @:VS_DEPT
   AND TO_CHAR(PERF.SALES_DATE, 'YYYY') = :VS_YEAR
 GROUP BY CASE
        	WHEN :VS_DEPT = '' THEN '전체'
        	ELSE D.DEPT_NAME
       	  END 
	    , PERF.SALES_DATE
 ORDER BY TO_CHAR(PERF.SALES_DATE, 'YYYY-MM')