(
  SELECT E.EMP_NAME || '님 - 올해 1위' AS ALM
       , TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD') AS DATE
    FROM SM_SALES_PERFORMANCE PERF
    LEFT JOIN SM_EMPLOYEE E
      ON PERF.EMP_ID = E.EMP_ID
   WHERE TO_CHAR(PERF.SALES_DATE, 'YYYY') = :VS_YEAR
   GROUP BY E.EMP_ID, E.EMP_NAME
   ORDER BY SUM(PERF.NET_AMOUNT) DESC
   LIMIT 1
)
   UNION ALL
(
  SELECT D.DEPT_NAME || ' 달성률 '
         || ROUND((SUM(PERF.NET_AMOUNT) / NULLIF(SUM(PLN.TARGET_AMT), 0)) * 100, 1)
         || '%' AS ALM
		 , TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD') AS DATE
    FROM SM_SALES_PERFORMANCE PERF
    LEFT JOIN SM_SALES_PLAN PLN
      ON PLN.PROD_ID = PERF.PROD_ID
    LEFT JOIN SM_EMPLOYEE E
      ON PERF.EMP_ID = E.EMP_ID
    LEFT JOIN SM_DEPARTMENT D
      ON E.DEPT_ID = D.DEPT_ID
   GROUP BY D.DEPT_NAME
   ORDER BY (SUM(PERF.NET_AMOUNT) / NULLIF(SUM(PLN.TARGET_AMT), 0)) ASC
   LIMIT 1
)
UNION ALL
(
	SELECT PERF.REMARKS AS ALM
	     , TO_CHAR(PERF.SALES_DATE, 'YYYY-MM-DD') AS DATE
	  FROM SM_SALES_PERFORMANCE PERF
	 ORDER BY SALES_DATE DESC
	 LIMIT 1

)