SELECT SP.PLAN_ID	
	 , SP.PLAN_YEAR || '-' || SP.PLAN_MONTH AS PLAN_YM	
	 , E.EMP_NAME AS EMP_NAME	
	 , P.PROD_NAME AS PROD_NAME	
	 , SP.TARGET_QTY AS TARGET_QTY	
	 , SP.TARGET_AMT AS TARGET_AMT	
	 , CG.CODE_NAME AS PLAN_STATUS	
  FROM SM_SALES_PLAN	SP
LEFT JOIN SM_EMPLOYEE	E
	   ON SP.EMP_ID = E.EMP_ID
LEFT JOIN SM_PRODUCT	P
	   ON SP.PROD_ID = P.PROD_ID
LEFT JOIN SM_COMMON_CODE	CG
	   ON CG.GROUP_CD = 'PLAN_STATUS'
	  AND SP.PLAN_STATUS = CG.CODE
 WHERE 1=1
   AND CONCAT(SP.PLAN_YEAR, SP.PLAN_MONTH) = (@:VS_YM)
   AND SP.EMP_ID IN (@:VS_PIC)
   AND SP.PLAN_STATUS IN (@:VS_STATUS)