SELECT I.INV_ID		 AS INV_ID 			-- 재고ID
	 , P.PROD_NAME	 AS PROD_NAME		-- 제품명
	 , C.CODE_NAME 	 AS CATEGORY		-- 카테고리
	 , I.STORAGE_LOC AS STORAGE			-- 창고
	 , I.CURR_QTY 	 AS CURR_QTY 		-- 현재 재고
	 , I.SAFE_QTY 	 AS SAFE_QTY 		-- 안전 재고
	 , CASE P.SALE_YN WHEN 'Y' THEN '판매중'
	 				  WHEN 'N' THEN '판매중단'
	   END 			 AS STATUS 			-- 상태
	 , I.CREATED_AT	 AS RECEIVING_DATE	-- 최종 입고일
	 , P.CATEGORY	 AS CATEGORY_CODE	-- 카테고리 코드
	 , I.PROD_ID 	 AS PROD_CODE		-- 제품 코드
	 , I.UPDATED_AT	 AS SHIPPING_DATE	-- 최종 출고일
  FROM SM_INVENTORY I
  LEFT JOIN SM_PRODUCT P
	ON I.PROD_ID = P.PROD_ID
  LEFT JOIN SM_COMMON_CODE C
	ON C.GROUP_CD = 'PROD_CATEGORY'
	AND P.CATEGORY = C.CODE
 WHERE 1=1
   AND P.CATEGORY 	 IN (@:VS_CATEGORY)
   AND I.STORAGE_LOC IN (@:VS_WAREHOUSE)
   AND P.PROD_NAME 	 LIKE '%'||@:VS_KEYWORD||'%'