SELECT
      TO_CHAR(COUNT(DISTINCT I.PROD_ID), 'FM999,999,999,999')||'종'		AS TOTAL_ITEM_COUNT
    , TO_CHAR(SUM(I.CURR_QTY), 'FM999,999,999,999')||'개'				AS TOTAL_STOCK_QTY
    , TO_CHAR(SUM(CASE 
            WHEN I.CURR_QTY < I.SAFE_QTY THEN 1 
            ELSE 0 
          END), 'FM999,999,999,999')||'건'								AS UNDER_SAFETY_STOCK_COUNT
	, SUM(CASE 
            WHEN I.CURR_QTY < I.SAFE_QTY THEN 1 
            ELSE 0 
          END)															AS UNDER_SAFETY_STOCK_COUNT_VAL
    , '₩'||TO_CHAR(SUM(I.CURR_QTY * P.STD_PRICE), 'FM999,999,999,999') 	AS TOTAL_STOCK_VALUE
FROM SM_INVENTORY I
LEFT JOIN SM_PRODUCT P
  ON I.PROD_ID = P.PROD_ID
WHERE P.SALE_YN = 'Y'