 SELECT  T1.REPORT_CODE
 		, T1.FORM_SEQ 
 		, T1.FORM_NAME
 		, T1.VISIBLE 
		, T1.LAYOUT_MODEL
 		, T1.CREATE_USER
 		, T1.CREATE_DATE
 		, T1.MODIFY_USER
 		, T1.MODIFY_DATE
 FROM AUD_DOC_FORM T1 
 WHERE T1.REPORT_CODE = :VS_REPORT_CODE
 ORDER BY T1.FORM_SEQ ASC