SELECT  T1.REPORT_CODE 
 		, T1.REPORT_NAME
 		, T1.REPORT_DESC
		, T2.REPORT_CODE AS AUD_REPORT
 		, T1.CREATE_USER
 		, T1.CREATE_DATE
 		, T1.MODIFY_USER
 		, T1.MODIFY_DATE
		, '[디자이너]' AS CMD_DESIGNER
		, '[편집]' AS CMD_EDIT
 FROM AUD_DOC_REPORT T1 
 LEFT OUTER JOIN MTX_REPORT T2
 		ON T1.REPORT_CODE = T2.REPORT_CODE
 WHERE T1.FOLDER_CODE = :VS_FOLDER_CODE
   AND T1.REPORT_NAME LIKE %:VS_REPORT_NAME_KW%