SELECT PFM.SALES_ID AS SALES_ID
	 , TO_CHAR(PFM.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
	 , C.CUST_NAME AS CUST_NAME
	 , P.PROD_NAME AS PROD_NAME
	 , PFM.QTY AS QTY
	 , PFM.NET_AMOUNT AS NET_AMOUNT
	 , CG.CODE_NAME AS SALES_STATUS
  FROM SM_SALES_PERFORMANCE	PFM
  LEFT JOIN SM_CUSTOMER	C
	ON PFM.CUST_ID = C.CUST_ID
  LEFT JOIN SM_PRODUCT	P
	ON PFM.PROD_ID = P.PROD_ID
  LEFT JOIN SM_COMMON_CODE	CG
	ON CG.GROUP_CD = 'SALES_STATUS'
   AND PFM.SALES_STATUS = CG.CODE
 WHERE TO_CHAR(PFM.SALES_DATE,'YYYY') = :VS_YEAR
 ORDER BY PFM.SALES_ID