 SELECT  T1.CONTROL_CODE 		AS CONTROL_CODE 
        , T1.CONTROL_TYPE       AS CONTROL_TYPE
 		, T1.CONTROL_NAME 		AS CONTROL_NAME
		, T1.VAR_NAMES     		AS VAR_NAMES 
 		, T1.CONTROL_DESC 		AS CONTROL_DESC 
 		, T1.CONTROL_BODY 		AS CONTROL_BODY 
 		, T1.CONTROL_WIDTH 		AS CONTROL_WIDTH 
 		, T1.CONTROL_HEIGHT 	AS CONTROL_HEIGHT 
 		, T1.DELETE_YN 			AS DELETE_YN 
 		, T1.CREATE_USER 		AS CREATE_USER 
 		, T1.CREATE_DATE 		AS CREATE_DATE 
 		, T1.MODIFY_USER 		AS MODIFY_USER 
 		, T1.MODIFY_DATE 		AS MODIFY_DATE 
 FROM AUD_USER_CONTROL T1 
 WHERE T1.DELETE_YN <> :VS_USE_YN
 	AND ( T1.CONTROL_NAME LIKE %@:VS_CONTROL_KW%
 	OR  T1.CONTROL_DESC  LIKE %@:VS_CONTROL_KW% )

ORDER BY T1.CONTROL_NAME  ASC 	