SELECT SP.SALES_ID
	 , SP.SALES_DATE
	 , E.EMP_NAME
	 , C.CUST_NAME
	 , P.PROD_NAME
	 , CG_CAT.CODE_NAME		AS CATEGORY_NAME
	 , SP.QTY
	 , SP.UNIT_PRICE
	 , SP.COST_AMOUNT
	 , SP.NET_AMOUNT
	 , SP.SALES_STATUS			AS STATUS_CODE
	 , CG_ST.CODE_NAME			AS SALES_STATUS
  FROM SM_SALES_PERFORMANCE  SP
  LEFT JOIN SM_EMPLOYEE      E
	ON SP.EMP_ID = E.EMP_ID
  LEFT JOIN SM_CUSTOMER      C
	ON SP.CUST_ID = C.CUST_ID
  LEFT JOIN SM_PRODUCT       P
	ON SP.PROD_ID = P.PROD_ID
  LEFT JOIN SM_COMMON_CODE   CG_CAT
	ON CG_CAT.GROUP_CD = 'PROD_CATEGORY'
   AND P.CATEGORY = CG_CAT.CODE
  LEFT JOIN SM_COMMON_CODE   CG_ST
	ON CG_ST.GROUP_CD = 'SALES_STATUS'
   AND SP.SALES_STATUS = CG_ST.CODE
 WHERE 1=1
  -- AND TO_CHAR(SP.SALES_DATE, 'YYYY') = @:VS_YEAR
 ORDER BY SP.SALES_ID
