WITH BASE AS (
    SELECT CASE EXTRACT(DOW FROM S.SALES_DATE)
             WHEN 1 THEN '월'
             WHEN 2 THEN '화'
             WHEN 3 THEN '수'
             WHEN 4 THEN '목'
             WHEN 5 THEN '금'
           END AS WEEKDAY
         , S.SALES_ID
         , S.NET_AMOUNT
    FROM SM_SALES_PERFORMANCE S
    WHERE TO_CHAR(S.SALES_DATE,'YYYY') = :VS_YEAR
      AND S.SALES_STATUS = 'COMPLETED'
      AND EXTRACT(DOW FROM S.SALES_DATE) BETWEEN 1 AND 5
),
WEEKDAY_SALES AS (
    SELECT WEEKDAY
         , COUNT(DISTINCT SALES_ID) AS ORDER_CNT
         , SUM(NET_AMOUNT)          AS SALES_AMOUNT
    FROM BASE
    GROUP BY WEEKDAY
),
WEEKDAY_FIX AS (
    SELECT '월' AS WEEKDAY, 1 AS ORD UNION ALL
    SELECT '화', 2 UNION ALL
    SELECT '수', 3 UNION ALL
    SELECT '목', 4 UNION ALL
    SELECT '금', 5
)
SELECT F.WEEKDAY
     , W.ORDER_CNT
     , W.SALES_AMOUNT
FROM WEEKDAY_FIX F
LEFT JOIN WEEKDAY_SALES W
  ON F.WEEKDAY = W.WEEKDAY
ORDER BY F.ORD