SELECT P.CATEGORY AS CATEGORY
     , SUM(S.NET_AMOUNT) AS SALES_AMOUNT
     , SUM(S.NET_AMOUNT) / NULLIF(SUM(SUM(S.NET_AMOUNT)) OVER(),0) AS SALES_RATIO
FROM SM_SALES_PERFORMANCE S
JOIN SM_PRODUCT P
  ON S.PROD_ID = P.PROD_ID
WHERE TO_CHAR(S.SALES_DATE,'YYYY') = :VS_YEAR
GROUP BY P.CATEGORY
ORDER BY SALES_AMOUNT DESC
FETCH FIRST 5 ROWS ONLY